# fly.toml app configuration file generated for happycards on 2023-04-28T06:35:02+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "happycards"
primary_region = "lhr"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"